### ISSUE TITLE
DNS Address Could Not Be Found

### ISSUE THREAD

**Issue by 2016rshah** [tfausak/blunt#32]
Hey, I tried to use [pointfree.info](http://pointfree.info/) today and couldn't get to the site because the DNS server could not be found. The problem was `ERR_NAME_NOT_RESOLVED`, any idea what might be wrong?

**Comment by tfausak** [comment]
Yup, sorry. I am not maintaining Blunt anymore. You can try <http://pointfree.io/> instead.
